### ISSUE TITLE
Iterable returned from doTransformStuf does not support multiple calls to iterator()

### ISSUE THREAD

**Issue by gravelld** [mathieubolla/guava-utils#2]
An `Iterable` should be able to handle multiple calls to `iterator()` and return a fresh `Iterator` capable of iterating over the elements in the `Iterable`.

Because `sourceIterator` is declared before the `Iterable`, this doesn't work. To fix:

```
[...]
    return new Iterable<U>() {
        public Iterator<U> iterator() {
            final LinkedBlockingQueue<FutureTask<U>> queue = new LinkedBlockingQueue<FutureTask<U>>(factor);
            final Iterator<T> sourceIterator = source.iterator();
            return new AbstractIterator<U>() {
[...]
```

Now the iterator is reset on each call.

**Comment by mathieubolla** [comment]
Well spotted. Would you create a pull request? This would give you credits for the fix, and give me my first pull request ever so I get to see how it all works…

Thanks,

Mathieu

**Comment by gravelld** [comment]
Done that... closing this.
